### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'close')

### ISSUE THREAD

**Issue by cristhian-bento** [google-pay/google-pay-button#217]
**Describe the bug** An error is being thrown by pay.js when opening/closing the Google Pay window several times

**To Reproduce**:

1. Click on the Google Pay button (like if you want to break it).
2. Close the Google Pay window (try to break it again).
3. Repeat 1 and 2 until you get the error.

**Expected behavior** We expect it to not fail, so Sentry is not alarming us all the time.

**Screenshots**

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/103455424/229901716-653c7acc-e67d-427d-ad5e-5815b753675e.png">

**Component information:**

- Component
  - [x] React component (`@google-pay/button-react`)
  - [ ] Custom element (`@google-pay/button-element`)
  - [ ] Angular component (`@google-pay/button-angular`)
- Component version (e.g. 1.0.0):

**Environment:**

- Device (e.g. PC):
- OS (e.g. Windows 10):
- Browser (e.g. Edge 111.0.1661)
- Country/region: USA

**Additional context** It also happens in many other devices and OS/Browsers. E.g Samsung S21 Ultra / Samsung Mobile browser

**Comment by dmengelt** [comment]
@cristhian-bento thank for reporting this. we will take a closer look and report back.

**Comment by johnratignier** [comment]
Hey, we still have this issue raising a lot of time, any news about fix?

**Comment by dmengelt** [comment]
@johnratignier just checked today 😉 I should be able to give you an update by the end of the week

**Comment by dmengelt** [comment]
@johnratignier the issue is on our list. so sorry for not being able to give you more details for now...

**Comment by dmengelt** [comment]
@johnratignier do you still see this issue? if yes, are you able to reproduce this without Sentry?

**Comment by johnratignier** [comment]
> @johnratignier do you still see this issue? if yes, are you able to reproduce this without Sentry?
In which version (we are still in v3.0.9 for now)? And yes I managed to reproduce it when I reported, didn't try again since
<img width="351" alt="Capture d’écran 2023-08-31 à 16 29 54" src="https://github.com/google-pay/google-pay-button/assets/26454483/c325e162-a66b-4126-a683-d756dc5d8088">

**Comment by cristhian-bento** [comment]
just to add, we are still seeing this issue (as you can see, it started 8 months ago):
<img width="322" alt="image" src="https://github.com/google-pay/google-pay-button/assets/103455424/95dce400-e3e5-47a6-a0c2-341aa8f59190">

**Comment by dmengelt** [comment]
testing with 3.0.9 is fine. do you also see the issue here: https://google-pay-react-tbnfni.stackblitz.io/

**Comment by cristhian-bento** [comment]
I've just tested in Safari:

<img width="1309" alt="image" src="https://github.com/google-pay/google-pay-button/assets/103455424/fc534df5-23ee-4180-bcdf-ac09cae04632">

Not the same error, but same issue after following my steps to reproduce.

Safari Version 15.4 (17613.1.17.1.13)

**Comment by sergey-navrotskiy** [comment]
We've got this error too. But in other case. We using @google-pay/button-element & Vue. Page with GooglePayButton openes in iframe & this error fired when iframe closed (all browsers, macos)

**Comment by dmengelt** [comment]
@sergey-navrotskiy are you able to create a reproducer and share it here?

**Comment by sergey-navrotskiy** [comment]
@dmengelt sorry

We've turn off google pay on production server and I can`t checked it now.  On staging server now this error is absent – so maybe its fixed. I will wrote if this error appears.

**Comment by johnratignier** [comment]
> @cristhian-bento / @johnratignier we deployed a fix for this error. Could you check again?

Does it need a new version? Seems only one error in the past 24h, 15h ago. And 15 occurences in the past 7days, that's far less than before, but we also have less trafic

**Comment by dmengelt** [comment]
@johnratignier No new version needed. The fix is part of `pay.js` 
> Seems only one error in the past 24h, 15h ago.

Yeah we deployed the fix around `22:00 Sep 19 GMT+2`

**Comment by cristhian-bento** [comment]
@dmengelt I was not able to manually reproduce it anymore. I will check the logs, but seems fixed. Thanks!

**Comment by dmengelt** [comment]
@cristhian-bento thanks! please report back after checking the logs.

**Comment by cristhian-bento** [comment]
kind of weird, I can still see it in Sentry, but only 8 times/day, which I think is acceptable.


<img width="1419" alt="image" src="https://github.com/google-pay/google-pay-button/assets/103455424/83c11709-e0aa-4dbc-ae1b-f04278b03098">

**Comment by dmengelt** [comment]
@cristhian-bento any chance that there is some caching involved?

**Comment by sergey-navrotskiy** [comment]
@dmengelt, here the reproducer: [GooglePayError.zip](https://github.com/google-pay/google-pay-button/files/12750496/GooglePayError.zip)

The code causing the error: 
`button.addEventListener('loadpaymentdata', event => {
          location=`./3dsv2.html` // redirectTo3dsUrl
      });`

**Comment by dmengelt** [comment]
@sergey-navrotskiy thanks for the reproducer. I believe that your problem is not the same. Also, your code works for me.

Do you maybe want to open a new issue and share the error message? (A screenshot should do it)

**Comment by sergey-navrotskiy** [comment]
![Знімок екрана 2023-09-28 о 17 43 40](https://github.com/google-pay/google-pay-button/assets/1263960/dfa59ef3-566d-4adf-b23f-dc3a226a0a46)

**Comment by dmengelt** [comment]
@sergey-navrotskiy and you are just clicking on "Show iframe" in your example and then complete a Google Pay transaction in order to get this error?

**Comment by sergey-navrotskiy** [comment]
@dmengelt 

https://github.com/google-pay/google-pay-button/assets/1263960/f6f461e0-a631-4e99-b91d-47741962fc3e

**Comment by dmengelt** [comment]
@sergey-navrotskiy can you do another video here please: https://google-pay-custom-element-g8nuum.stackblitz.io

Please share the video even if you don't see the error.

**Comment by dmengelt** [comment]
Another question @sergey-navrotskiy: You load your iframe content from the same domain as your main page right? So everything is on `localhost:63342`?

**Comment by sergey-navrotskiy** [comment]
@dmengelt , I guess I don't have access there (https://google-pay-custom-element-g8nuum.stackblitz.io/)
![Знімок екрана 2023-09-28 о 18 02 46](https://github.com/google-pay/google-pay-button/assets/1263960/aa6c4079-dfcd-4291-8a33-a91e08aab9a1)

**Comment by dmengelt** [comment]
@sergey-navrotskiy please do a video here: https://gpay-live-demo.web.app/

**Comment by sergey-navrotskiy** [comment]
@dmengelt, there is no error on your page (https://gpay-live-demo.web.app/)

https://github.com/google-pay/google-pay-button/assets/1263960/05bf93c7-8afc-4ab5-9db4-f8e20f8abec3

**Comment by dmengelt** [comment]
@sergey-navrotskiy thanks. I'm unable to reproduce 😕

Also, I'm wondering why you always see the popup instead of the Payment Request / Payment Handler UI. What browser version are you using? I can see that you have the `allowpaymentrequest` attribute (you can migrate this to `allow="payment *"`) on your iframe.

**Comment by sergey-navrotskiy** [comment]
@dmengelt , 
Apple M2 Pro, MacOs Ventura 13.5.2 (22G91)
I`ve got this error in Chrome 117.0.5938.132 (arm64), Safari, FF

I set `allow="payment *"`, but the error still exists


![crome](https://github.com/google-pay/google-pay-button/assets/1263960/e9bb9f99-e367-4ecb-8f7b-08cc6d1abef3)
![ff](https://github.com/google-pay/google-pay-button/assets/1263960/d89af3e8-e759-4e30-86b4-e3c58ba5ed21)
![safari](https://github.com/google-pay/google-pay-button/assets/1263960/fd0d794d-0f09-4a1a-907c-87d2daddb49d)

**Comment by dmengelt** [comment]
@sergey-navrotskiy yeah the `allow="payment *"` hint was not supposed to fix your issue 😉 

Could you send me a screenshot of what you see on this page: https://dmengelt.github.io/gpay-web-tester/pr/

**Comment by sergey-navrotskiy** [comment]
@dmengelt 
![u](https://github.com/google-pay/google-pay-button/assets/1263960/f6bf3c5a-423c-4da9-9920-9d545a72aa0a)

**Comment by sergey-navrotskiy** [comment]
@dmengelt, this screenshot is better ;)
![Знімок екрана 2023-09-28 о 19 41 54](https://github.com/google-pay/google-pay-button/assets/1263960/93807747-87fd-4c0f-9efa-35e8141c9f15)

**Comment by dmengelt** [comment]
Ok it turns out that the error message gets triggered with the following browser settings active:

<img width="753" alt="image" src="https://github.com/google-pay/google-pay-button/assets/4389374/8115c93e-1a7a-42b5-90b9-b4ddd0751491">

For Chrome those settings can be found under `chrome://settings/payments`

If `Allow sites to check if you have payment methods saved` is turned off, we fallback to the "pop-up" flow and in this scenario we try to close a window on `beforeunload` if the site navigates away. This window is sometimes not available and therefore this produces the `Uncaught TypeError: Cannot read properties of null (reading 'close')` error.

We will look into this. Sorry for all the inconvenience.

**Comment by dmengelt** [comment]
@cristhian-bento / @johnratignier we deployed a second fix. Could you check your Sentry logs once more? The fix is live since ~ 22:00 CET 11. Oct.

**Comment by dmengelt** [comment]
friendly ping @cristhian-bento / @johnratignier - I would love to close this issue 😉

**Comment by johnratignier** [comment]
146 occurences the last 30 days but as said, we have far less traffic since the end of the summer.
Last issue 2 days ago. I would be 100% sure in the next 2 weeks, but for now looks good :)

**Comment by dmengelt** [comment]
@johnratignier thank you! alright... please report back in 2 weeks

**Comment by dmengelt** [comment]
@johnratignier could you do another check?

**Comment by johnratignier** [comment]
Hi @dmengelt it seems no new error since 11 october, I think can be close! Thanks a lot for the fix! :)

**Comment by dmengelt** [comment]
@johnratignier nice! thanks for the heads up. closing...
